/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
//import controlador
import Modelo.BD_Persona;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import Modelo.Cuidadano;
import Modelo.Indigena;
import Modelo.Migrante;
import Modelo.Refugiado;
/**
 *
 * @author David
 */
public class VentanaMigración extends javax.swing.JFrame {

    public Cuidadano ciudadano;
    public Indigena indio;
    public Migrante migrante;
    public Refugiado refugiado;
    /**
     * Creates new form VentanaMigración
     */
    public VentanaMigración() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(rB_cuidadano);
        group.add(rB_indigena);
        group.add(rB_Migrante);
        group.add(rB_Refuiado);
        rB_cuidadano.setSelected(true);
        ciudadano=new Cuidadano();
        indio=new Indigena();
        migrante=new Migrante();
        refugiado=new Refugiado();
        
        //controlador
    }
    public String regresarNombre(){
        String nombre="";
        
        if(rB_cuidadano.isSelected()){
            nombre=ciudadano.getNombre();
        }
        else if(rB_indigena.isSelected()){
            nombre=indio.getNombre();
        }
        else if(rB_Migrante.isSelected()){
            nombre=migrante.getNombre();
        }
        else if(rB_Refuiado.isSelected())
        {
        nombre=refugiado.getNombre();
        }
        return nombre;
    }//fin del constructor
    
     public void setJlMensajes(String jlMensajes) {
        this.jlMensajes.setText(jlMensajes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Nomb = new javax.swing.JLabel();
        jL_Id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTex_Nomb = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jText_id = new javax.swing.JTextArea();
        rB_cuidadano = new javax.swing.JRadioButton();
        rB_indigena = new javax.swing.JRadioButton();
        rB_Migrante = new javax.swing.JRadioButton();
        rB_Refuiado = new javax.swing.JRadioButton();
        jL_Estado = new javax.swing.JLabel();
        jB_Agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlMensajes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_Nomb.setText("Nombre del solicitante");

        jL_Id.setText("Documento de Identificacion");

        jTex_Nomb.setColumns(20);
        jTex_Nomb.setRows(5);
        jScrollPane1.setViewportView(jTex_Nomb);

        jText_id.setColumns(20);
        jText_id.setRows(5);
        jScrollPane2.setViewportView(jText_id);

        rB_cuidadano.setText("Cuidadano");

        rB_indigena.setText("Indigena");

        rB_Migrante.setText("Migrante");

        rB_Refuiado.setText("Refugido");

        jL_Estado.setText("Seleccione su estado");

        jB_Agregar.setText("Agregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_Estado, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rB_cuidadano)
                        .addGap(18, 18, 18)
                        .addComponent(rB_indigena)
                        .addGap(34, 34, 34)
                        .addComponent(rB_Migrante)
                        .addGap(47, 47, 47)
                        .addComponent(rB_Refuiado)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Nomb, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Nomb, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rB_cuidadano)
                    .addComponent(rB_indigena)
                    .addComponent(rB_Migrante)
                    .addComponent(rB_Refuiado)
                    .addComponent(jL_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMigración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMigración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMigración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMigración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMigración().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Agregar;
    private javax.swing.JLabel jL_Estado;
    private javax.swing.JLabel jL_Id;
    private javax.swing.JLabel jL_Nomb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTex_Nomb;
    private javax.swing.JTextArea jText_id;
    private javax.swing.JLabel jlMensajes;
    private javax.swing.JRadioButton rB_Migrante;
    private javax.swing.JRadioButton rB_Refuiado;
    private javax.swing.JRadioButton rB_cuidadano;
    private javax.swing.JRadioButton rB_indigena;
    // End of variables declaration//GEN-END:variables

    private class jlMensajes {

        public jlMensajes() {
        }
    }
}
